# Generated by Django 4.1.7 on 2023-03-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aluno', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('matricula', models.CharField(max_length=8)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disciplina', models.IntegerField()),
                ('id_professor', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=7)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_frequencia', models.IntegerField()),
                ('dia', models.DateField()),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='controle_de_frequencia.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_professor', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('rg', models.CharField(max_length=8)),
                ('codigo', models.CharField(max_length=8)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plano_aula', models.IntegerField()),
                ('tema_aula', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('metodo', models.CharField(choices=[('teorica', 'teorica'), ('pratica', 'pratica')], max_length=50)),
                ('dia', models.DateField()),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina', to='controle_de_frequencia.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='FrequenciaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_frequencia_aluno', models.IntegerField()),
                ('presenca', models.BooleanField(default=True)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='controle_de_frequencia.alunos')),
                ('id_frequencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia', to='controle_de_frequencia.frequencia')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default=0.0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_aluno', to='controle_de_frequencia.alunos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno_disciplina', to='controle_de_frequencia.disciplinas')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplina_matricula', to='controle_de_frequencia.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atividade', models.IntegerField()),
                ('atividade', models.TextField()),
                ('tipo', models.CharField(choices=[('ATIVIDADE_DE_SALA', 'sala'), ('ATIVIDADE_DE_CASA', 'casa'), ('PROVA', 'prova')], max_length=50)),
                ('data_postagem', models.DateField()),
                ('data_entrega', models.DateField()),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_disciplina', to='controle_de_frequencia.disciplinas')),
                ('id_plano_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_aula', to='controle_de_frequencia.planoaula')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_atividade_aluno', models.IntegerField()),
                ('nota', models.FloatField()),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_id_aluno', to='controle_de_frequencia.alunos')),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_id', to='controle_de_frequencia.atividades')),
            ],
        ),
    ]
